CP-22306: add verify release notes and stubbed approval step

diff --git a/.github/workflows/build-and-publish-beta-chart.yml b/.github/workflows/build-and-publish-beta-chart.yml
--- a/.github/workflows/build-and-publish-beta-chart.yml
+++ b/.github/workflows/build-and-publish-beta-chart.yml
@@ -62,6 +62,25 @@ jobs:
           VERSION_LINE=$(awk '/version:/ && !done {print NR; done=1}' charts/cloudzero-agent/Chart.yaml)
           sed -i ''$VERSION_LINE's/.*/version: ${{ env.NEW_VERSION }}/' charts/cloudzero-agent/Chart.yaml
 
+      - name: Validate Release Notes are Present
+        run: |
+          if [ ! -f "charts/cloudzero-agent/docs/releases/${{ env.NEW_VERSION }}.md" ]; then
+            echo "Release notes for ${{ env.NEW_VERSION }} are missing. Please create a release notes file at charts/cloudzero-agent/docs/releases/${{ env.NEW_VERSION }}.md"
+            exit 1
+          fi
+
+      - name: Product Management Approval
+        uses: trstringer/manual-approval@v1
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          approvers: cloudzero/product-management
+          minimum-approvals: 1
+          issue-title: "Releasing ${{ env.NEW_VERSION }}"
+          issue-body: "Please approve or deny the release notes in charts/cloudzero-agent/docs/releases/${{ env.NEW_VERSION }}.md"
+          exclude-workflow-initiator-as-approver: false
+          additional-approved-words: ''
+          additional-denied-words: ''
+
       # Step 4: Package and Commit Chart
       - name: Package Chart
         run: helm package charts/cloudzero-agent/ --destination .deploy
@@ -126,11 +145,4 @@ jobs:
           files: .deploy/cloudzero-agent-${{ env.NEW_VERSION }}.tgz
           make_latest: false
           target_commitish: ${{ env.COMMIT_HASH }}
-          body: |
-            ## Installation Instructions
-      
-            [Please follow the Installation Instructions provided in this releases README](https://github.com/Cloudzero/cloudzero-charts/blob/${{ env.NEW_VERSION }}/charts/cloudzero-agent/README.md).
-      
-            ## Release ${{ env.NEW_VERSION }} Changes
-      
-            ${{ steps.get_changes.outputs.changes }}
+          body_path: ${{ github.workspace }}/charts/cloudzero-agent/docs/releases/${{ env.NEW_VERSION }}.md
diff --git a/.github/workflows/build-and-publish-chart.yml b/.github/workflows/build-and-publish-chart.yml
--- a/.github/workflows/build-and-publish-chart.yml
+++ b/.github/workflows/build-and-publish-chart.yml
@@ -47,10 +47,6 @@ jobs:
       - name: Install Helm
         uses: azure/setup-helm@v3
 
-      - name: Build Dependencies
-        run: helm dependency update charts/cloudzero-agent/
-
-
       # Step 4: Determine Version
       - name: Get Github Tag Version
         id: version
@@ -68,6 +64,30 @@ jobs:
         run: |
           VERSION_LINE=$(awk '/version:/ && !done {print NR; done=1}' charts/cloudzero-agent/Chart.yaml)
           sed -i ''$VERSION_LINE's/.*/version: ${{ env.NEW_VERSION }}/' charts/cloudzero-agent/Chart.yaml
+
+      - name: Validate Release Notes are Present
+        run: |
+          if [ ! -f "charts/cloudzero-agent/docs/releases/${{ env.NEW_VERSION }}.md" ]; then
+            echo "Release notes for ${{ env.NEW_VERSION }} are missing. Please create a release notes file at charts/cloudzero-agent/docs/releases/${{ env.NEW_VERSION }}.md"
+            exit 1
+          fi
+
+      # - name: Generate token
+      #   id: generate_token
+      #   uses: tibdex/github-app-token@v1
+      #   with:
+      #     app_id: ${{ secrets.APP_ID }}
+      #     private_key: ${{ secrets.APP_PRIVATE_KEY }}
+
+      # - name: Wait for Product Management Approval
+      #   uses: trstringer/manual-approval@v1
+      #   with:
+      #     secret: ${{ steps.generate_token.outputs.token }}
+      #     approvers: cloudzero/product-management
+      #     minimum-approvals: 1
+
+      - name: Build Dependencies
+        run: helm dependency update charts/cloudzero-agent/
 
       # Step 5: Package and Commit Chart
       - name: Package Chart
@@ -144,12 +164,5 @@ jobs:
           files: cloudzero-agent-${{ env.NEW_VERSION }}.tgz
           make_latest: true
           target_commitish: ${{ env.COMMIT_HASH }}
-          body: |
-            ## Installation Instructions
-
-            [Please follow the Installation Instructions provided in this releases README](https://github.com/Cloudzero/cloudzero-charts/blob/${{ env.NEW_VERSION }}/charts/cloudzero-agent/README.md).
-
-            ## Release ${{ env.NEW_VERSION }} Changes
-
-            ${{ steps.get_changes.outputs.changes }}
+          body_path: ${{ github.workspace }}/charts/cloudzero-agent/docs/releases/${{ env.NEW_VERSION }}.md
 
